AnagramSolver.WebApp/Controllers/MVCControllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AnagramSolver.Contracts;
using AnagramSolver.EF.CodeFirst.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace AnagramSolver.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IWordService _wordService;
        private readonly ILogService _logService;
        private readonly ICachedWordService _cachedWordService;

        public HomeController(ILogger<HomeController> logger, IWordService wordService, ILogService logService, ICachedWordService cachedWordService)
        {
            _logger = logger;
            _wordService = wordService;
            _logService = logService;
            _cachedWordService = cachedWordService;
        }

        public async Task<IActionResult> Index(string word)
        {
            var ip = System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()).AddressList[1].ToString();

            if ((await _logService.Allowed(ip)))
            {
                var anagrams = _wordService.GetAnagrams(word);

                await _logService.AddUserLog(new UserLogEntity(ip, DateTime.Now, word, string.Join(',', anagrams), UserLogEntity.UserAction.Search));

                return View(new AnagramView() { Word = word, Anagrams = (await _wordService.GetAnagrams(word)), Allowed = true });
            }

            return View(new AnagramView() { Word = word, Anagrams = new List<string>(), Allowed = false });
        }
        public async Task<IActionResult> Blank()
        {
            return View();
        }
        public async Task<IActionResult> Remove(string word)
        {
            var ip = System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()).AddressList[1].ToString();

            await _cachedWordService.RemoveCachedWords(word, _wordService.DeleteWord(word).ToString());
            await _logService.AddUserLog(new UserLogEntity(ip, DateTime.Now, word, "", UserLogEntity.UserAction.Delete));

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddForm(string word, string category)
        {
            if(!string.IsNullOrEmpty(word) && !string.IsNullOrEmpty(category))
            {
                var ip = System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()).AddressList[1].ToString();

                await _wordService.AddWord(word, category);
                await _logService.AddUserLog(new UserLogEntity(ip, DateTime.Now, word, "", UserLogEntity.UserAction.Add));
            }

            return await Blank();
        }
        public async Task<IActionResult> AddForm()
        {
            return View();
        }
        public async Task<IActionResult> UpdateForm(string oldWord, string newWord)
        {
            ViewData["OldWord"] = oldWord;

            if (!string.IsNullOrEmpty(oldWord) && !string.IsNullOrEmpty(newWord))
            {
                var ip = System.Net.Dns.GetHostEntry(System.Net.Dns.GetHostName()).AddressList[1].ToString();

                await _cachedWordService.RemoveCachedWords(oldWord, _wordService.UpdateWord(oldWord, newWord).ToString());
                await _logService.AddUserLog(new UserLogEntity(ip, DateTime.Now, newWord, "", UserLogEntity.UserAction.Update));
            }

            return View();
        }
    }
}

AnagramSolver.WebApp/Controllers/MVCControllers/LogsController.cs
using AnagramSolver.Contracts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;

namespace AnagramSolver.WebApp.Controllers
{
    public class LogsController : Controller
    {
        private readonly ILogger<LogsController> _logger;
        private readonly ILogService _logService;
        public LogsController(ILogger<LogsController> logger, ILogService logService)
        {
            _logger = logger;
            _logService = logService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _logService.GetUserLogs());
        }
    }
}

AnagramSolver.WebApp/Controllers/MVCControllers/WordsController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AnagramSolver.Contracts;
using System.Threading.Tasks;

namespace AnagramSolver.WebApp.Controllers
{
    public class WordsController : Controller
    {
        private readonly ILogger<WordsController> _logger;
        private readonly IWordService _wordService;
        private const int PageSize = 100;

        public WordsController(ILogger<WordsController> logger, IWordService wordService)
        {
            _logger = logger;
            _wordService = wordService;
        }
        public async Task<IActionResult> Index(int pageNumber, string searchString)
        {
            ViewData["CurrentFilter"] = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                return View(await _wordService.GetWords(pageNumber, PageSize, searchString));
            }
            else
            {
                return View(await _wordService.GetWords(pageNumber, PageSize));
            }       
        }
    }
}

AnagramSolver.WebApp/Views/Home/AddForm.cshtml
@{
    Layout = null;
}

    <div style=" width:500px; margin: 0 auto; text-align: center">
        @using (Html.BeginForm())
        {
            <input type="text" title="žodis" name="Word" style="width: 100%; padding: 10px; border: solid black 1px" />
            <input type="text" title="kategorija" name="Category" style="width: 100%; padding: 10px; border: solid black 1px" />
            <input type="submit" value="Pridėti" style="width: 100%; margin-top: 10px; padding: 10px; border: solid black 1px" />
        }
        <a style="width: 500px; margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
           asp-controller="Home"
           asp-action="Blank">
            Pradžia
        </a>
    </div>

AnagramSolver.WebApp/Views/Home/Blank.cshtml
@{
    Layout = null;
}

    <div style="margin: 0 auto; text-align: center">
        <a style="margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
           asp-controller="Words"
           asp-action="Index"
           asp-route-pageNumber="1">
            Žodynas
        </a>
        <a style="margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
           asp-controller="Logs"
           asp-action="Index">
            Log'ai
        </a>
        <a style="margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
           asp-controller="Home"
           asp-action="AddForm">
            Naujas žodis
        </a>
    </div> 

AnagramSolver.WebApp/Views/Home/Index.cshtml
@model AnagramSolver.Contracts.AnagramView

@{
    Layout = null;
}

    <div style=" width:500px; margin: 0 auto; text-align: center">
        <h1>Žodžio "@Model.Word" anagramos</h1>
        @if (Model.Allowed)
        {
            <ul style="padding: 0; list-style-type: none">
                @foreach (string word in Model.Anagrams)
                {
                    <li style="padding: 10px; border: solid black 1px">@word</li>
                }
            </ul>
        }
        else
        {
            <p>Pasiektas leistinas anagramų paieškos skaičius, norėdami gauti papildomų paieškų pridėkite ar pakoreguokite žodyno žodį</p>
        }
        <a style="margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
           asp-controller="Home"
           asp-action="Remove"
           asp-route-word="@Model.Word">
            Ištrinti
        </a>
        <a style="margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
           asp-controller="Home"
           asp-action="UpdateForm"
           asp-route-oldWord="@Model.Word"
           asp-route-newWord="">
            Koreguoti
        </a>
    </div>

AnagramSolver.WebApp/Views/Home/Remove.cshtml
@{
    Layout = null;
}

<div style="margin: 0 auto; text-align: center">
    <a style="margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
       asp-controller="Home"
       asp-action="Blank">
        Pradžia
    </a>
</div> 

AnagramSolver.WebApp/Views/Home/UpdateForm.cshtml
@{
    Layout = null;
}

<div style=" width:500px; margin: 0 auto; text-align: center">
    @using (Html.BeginForm())
    {
        <input type="text" disabled value="@ViewData["OldWord"]" name="Word" style="width: 100%; padding: 10px; border: solid black 1px" />
        <input type="text" name="NewWord" style="width: 100%; padding: 10px; border: solid black 1px" />
        <input type="submit" value="Atnaujinti" style="width: 100%; margin-top: 10px; padding: 10px; border: solid black 1px" />
    }
    <a style="width: 500px; margin-top: 10px; padding: 10px; text-decoration: none; border: 1px solid black"
       asp-controller="Home"
       asp-action="Blank">
        Pradžia
    </a>
</div>